### ISSUE TITLE
TraderXTP的direction判断有问题

### ISSUE THREAD

**Issue by stonebj** [wondertrader/wondertrader#102]
XTP头文件里面写了这么一段，会导致direction相关判断，if始终进入else分支
> ///开平标志，期权用户关注字段，其余用户填0即可
> XTP_POSITION_EFFECT_TYPE    position_effect;

TradeXTP.CPP
inline WTSDirectionType wrapDirectionType(XTP_SIDE_TYPE side, XTP_POSITION_EFFECT_TYPE pe)
{
	if (XTP_SIDE_BUY == side)
		if (pe == XTP_POSITION_EFFECT_OPEN)
			return WDT_LONG;
		else
			return WDT_SHORT;  // 始终进入else
	else
		if (pe == XTP_POSITION_EFFECT_OPEN)
			return WDT_SHORT;
		else
			return WDT_LONG;  // 始终进入else
}

**Comment by wondertrader** [comment]
最新dev已修正
