### ISSUE TITLE
on_condition_triggered触发异常

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#103]
# 问题复现：

使用当前版本中demo时，在on_tick中设置limitprice和stopprice为0的直接触发单，也仍然会触发on_condition_triggered。但在on_schedule中，这样的直接触发单，则不会触发on_condition_triggered

# 原因分析

在on_tick中设置直接委托单时，_is_in_schedule为false，因此sInfo._triggered会被设置为true，导致后续在判断是否作为条件单触发回调时，出现非预期的回调情况。

**Comment by wondertrader** [comment]
这个我来改
