### ISSUE TITLE
python接口中的stra_get_ticks无法调用

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#112]
python接口中的stra_get_ticks无法调用，调用时会直接卡死，cpp中可以正常调用。通过调试，发现已经执行了WtBtPorter下的cta_get_ticks中的回调函数调用，所以问题应该是处在python那边的处理上

**Comment by wondertrader** [comment]
回测框架还是实盘框架？

**Comment by wondertrader** [comment]
应该解决了，如果有发现，再开
