### ISSUE TITLE
CTA引擎中，非条件单无法将变动传递给执行器

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#113]
https://github.com/wondertrader/wondertrader/blob/0d4b8616941250af129d9103207d61c5d17d2e6f/src/WtCore/CtaStraBaseCtx.cpp#L1441-L1444

该段中，导致非条件单的变动，无法传递给执行器，导致无法正常下单

**Comment by wondertrader** [comment]
最新dev已修复，将在v0.9.5发布
