### ISSUE TITLE
[bug]  在使用换月合约进行交易的情况下，可能会在换月当日出现问题

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#114]
假定当前时间为20日夜盘，此时发生了换月，主力合约由A-》B，但是可能会出现在当天夜盘交易的主力合约仍然是A，但是在第二天21日的白盘，主力切换到了B，导致出现了重复开仓的问题。目前猜测可能和交易日和日历日的获取有关，交易日最初是以日历日赋值，随后等第一个tick到达后，在重新设置成交易日。这个逻辑可能存在bug

**Comment by wondertrader** [comment]
dev应该已经修复
