### ISSUE TITLE
[bug] 关于HftMocker模块中procOrder 方法内调用on_order、on_trade的传参问题

### ISSUE THREAD

**Issue by zjzhiazhia** [wondertrader/wondertrader#117]
![image](https://user-images.githubusercontent.com/91235232/192217595-1d9d1d6b-7369-4cf3-b440-c0f7e8f4a2f9.png)
遇到的问题：高频回测模块中，策略在on_trade中调用ctx->stra_sell()会报错，当调用完ctx->stra_sell()后on_trade接收的指针参数stdCode指向了非法内存。
可能的原因：HftMocker中_orders在插入新订单发生扩容的时候，ordInfo会被复制到新地址，原有的ordInfo会被释放掉，此时作为参数传递的ordInfo._code就变成了野指针。

**Comment by wondertrader** [comment]
这个最新版的dev应该已经修复，改成了智能指针
