### ISSUE TITLE
试WtHftStraFact这个demo的时候发现在存在跳转错误的问题，导致无法订阅合约。

### ISSUE THREAD

**Issue by zimosky** [wondertrader/wondertrader#12]
**您好，我在调试WtHftStraFact这个demo的时候发现在存在跳转错误的问题，导致无法订阅合约。**
![image](https://user-images.githubusercontent.com/95108635/143661527-beed24d4-fce7-4e6d-9203-84d9a82b8d1b.png)
在WtHftStrDemo.cpp这个源码中void WtHftStraDemo::on_init(IHftStraCtx* ctx) 这个方法里面ctx->stra_sub_ticks(_code.c_str())跳转进去后是如下代码
![image](https://user-images.githubusercontent.com/95108635/143661698-ed6be2fc-9bd6-491b-bbd7-9d65463e348a.png)

double HftStraBaseCtx::stra_get_price(const char* stdCode)
{
	return _engine->get_cur_price(stdCode);
}
为什么不是跳转到如下：
void HftStraBaseCtx::stra_sub_ticks(const char* stdCode)
{
	_engine->sub_tick(id(), stdCode);
	stra_log_info("Market Data subscribed: %s", stdCode);
}

**Comment by wondertrader** [comment]
你好，谢谢关注Wondertrader！你这种情况，应该可以通过全部重新生成解决。还有一个，也有可能是因为你在release下调试，release会做一些优化，调试定位可能会出错。

**Comment by zimosky** [comment]
您好，我进行了全部重新生成解决方案，是Debug X64模式下进行的全部重新生成，调试也是在Debug下进行的。现在问题依然存在。
![image](https://user-images.githubusercontent.com/95108635/143665536-8717c0a0-ec43-4038-a270-6350e419fc66.png)
![image](https://user-images.githubusercontent.com/95108635/143665602-f2f9aa99-b779-4fb6-ae8c-f0667f597422.png)

**Comment by wondertrader** [comment]
我之前没遇到过，我先检查一下看看～你是调试的哪个工程？WtBtRunner？

**Comment by zimosky** [comment]
谢谢，麻烦您抽空看看。
我调试的是WtRunner这个工程。用的是HFT的那个demo,配置文件使用的是dist/WtRunner_win中的，就修改了Simsow中的账号信息。

**Comment by zimosky** [comment]
群主您好，我这边找到问题了，是应该将x64文件夹下面的WtHftStraFact.dll直接拷贝到WtRunner中，而不是在demo中重新生成工程，再拷贝过来。谢谢。
![image](https://user-images.githubusercontent.com/95108635/143686657-1a80b203-0705-4de5-b3b0-9b50be458754.png)

**Comment by wondertrader** [comment]
好的。解决了就好～

**Comment by wondertrader** [comment]
解决了我先关闭了~
