### ISSUE TITLE
在Hft引擎做A股股票做回测时，如果使用日线和tick，且有11:31至13:00休盘期间的tick时，13:00后的tick不会回放。

### ISSUE THREAD

**Issue by chenchenwenfeng** [wondertrader/wondertrader#120]
在Hft引擎做回测时，HisDataReplayer中有这个调用过程 run_by_bars  —>replayHftDatas —>getNextTickTime—>isInTradingTime。
isInTradingTime 判断中午休盘期间的tick不在交易时段，一路调用返回，导致退出了replayHftDatas 的执行，而日线驱动的回测，当天就不会再进入replayHftDatas 了，从而导致下午的tick没有机会回放。
下面两行代码是关键：
replayHftDatas函数中的：
```
_uint64_t nextTime = std::min(UINT64_MAX, getNextTickTime(_cur_tdate));
if (nextTime == UINT64_MAX)
   return false;_

```
getNextTickTime函数中的：
```
_//By Wesley @ 2022.03.06
//检查一下时间戳，如果不是交易时间的，就不回放了
if(!sInfo->isInTradingTime(nextTick.action_time/100000, false))_

```

**Comment by wondertrader** [comment]
dev已修复，正式版在0.9.8+
