### ISSUE TITLE
【HFT】_orders改成智能指针后不能解决这个问题

### ISSUE THREAD

**Issue by dongqiceo** [wondertrader/wondertrader#126]
改成智能指针后不能解决这个问题

_Originally posted by @dongqiceo in https://github.com/wondertrader/wondertrader/issues/62#issuecomment-1326031618_

**Comment by wondertrader** [comment]
我试试看

**Comment by dongqiceo** [comment]
> 我试试看

order的递归锁好像并没有锁住变量，一开始以为是同tick撮合的问题，改为false也不能解决

**Comment by wondertrader** [comment]
dev已修复，正式版0.9.8+
