### ISSUE TITLE
ParserCTP.cpp文件中配置判断逻辑是否有误?

### ISSUE THREAD

**Issue by dumengru** [wondertrader/wondertrader#127]
ParserAdapter.cpp文件中`ParserAdapter::init`要求配置中必须有"module", 因此ParserCTP.cpp文件中`ParserCTP::init`

```cpp
	std::string module = config->getCString("ctpmodule");
	if (module.empty())
		module = "thostmduserapi_se";
```
这段代码判断逻辑是否多余?

![image](https://user-images.githubusercontent.com/62230160/204104655-63e9b8f0-5c42-4c66-91b2-fd3c61acf0ef.png)

![image](https://user-images.githubusercontent.com/62230160/204104677-21e5e69d-962b-4148-b0bc-d70e6dc89ee4.png)

**Comment by wondertrader** [comment]
这里没有问题，你仔细看一下：module和ctpmodule是两个东西
