### ISSUE TITLE
WT中HFT模式下是否支持多周期的策略

### ISSUE THREAD

**Issue by zimosky** [wondertrader/wondertrader#13]
首先非常感谢您开源这么好的项目。我想咨询下，WT中HFT模式下是否支持多周期的策略，比如在我的策略中，需要几个周期进行共振的，比如1分钟，5分钟15分钟之类的，这样该如何订阅呢，我看HFTDEMO中有on_bar这个回调，但是如何订阅不同分钟数据，来触发这个回调函数呢？WT这个是否支持呢，如果支持，麻烦您指点下我该如何订阅多周期，我找了好久都没有找到。非常感谢。

**Comment by zimosky** [comment]
我是在C++模式下调试HFT的。

**Comment by wondertrader** [comment]
你好，HFT下同样支持，多周期策略

**Comment by wondertrader** [comment]
你好，如果有问题，可以加群讨论，issue一般用来提bug
