### ISSUE TITLE
疑似K线resample bug

### ISSUE THREAD

**Issue by dogfood1** [wondertrader/wondertrader#154]
### Discussed in https://github.com/wondertrader/wondertrader/discussions/153

<div type='discussions-op-text'>

<sup>Originally posted by **dogfood1** March 21, 2023</sup>
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/24435283/226411377-4b278cf6-a1db-4c65-b27c-f9b7830f9327.png">

在策略on_init中调用
context.stra_get_bars(code, 'm1', 199, isMain=True) 
在策略on_calculate中调用
df_bars = context.stra_get_bars(code, 'm60', 2) 

通过输出print(df_bars[-1]) 调试发现

比如202204130400 的收盘价是 39350.9
为04:00-04:04:59 的close(39350.9)

但如果获取了 m60 
那么202204130400(df_bars[-1]) 的close不应该是 2022-04-13 04:59:00的close price吗

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/24435283/226523824-9a93572e-21b6-4aa8-afa8-e39ac5bc4952.png">
疑似使用了未来信息，继续上面问题的close不正确问题

</div>

**Comment by wondertrader** [comment]
已经和提问者沟通了，他源数据有点问题，issue关掉了
