### ISSUE TITLE
TraderXTP的asyncio的work不启作用

### ISSUE THREAD

**Issue by pdkuionline** [wondertrader/wondertrader#162]
在TraderXTP 的connect 函数中，有如下代码：
void TraderXTP::connect()
{
	reconnect();

	if (_thrd_worker == NULL)
	{
		boost::asio::io_service::work work(_asyncio);
		_thrd_worker.reset(new StdThread([this](){
			while (true)
			{
				std::this_thread::sleep_for(std::chrono::milliseconds(2));
				_asyncio.run_one();
				//m_asyncIO.run();
			}
		}));
	}
}

经过实际测试发现，boost::asio::io_service::work work(_asyncio); 没有作用，后续往 asyncio 里面post 的Task 并没有被调用。 经过调试，发现,是 work 的作用域问题。 work 并没有工作在 thread 中。
可以修改成：
 void TraderXTP::connect()
{
	reconnect();

	if (_thrd_worker == NULL)
	{
		
		_thrd_worker.reset(new StdThread([this](){
                        boost::asio::io_service::work work(_asyncio);      //移动到这个位置
			while (true)
			{
				std::this_thread::sleep_for(std::chrono::milliseconds(2));
				_asyncio.run_one();
				//m_asyncIO.run();
			}
		}));
	}
}

搜索发现， 很多Trader 工程里，都有类似的代码，都有这个问题。

**Comment by wondertrader** [comment]
dev已修复
