### ISSUE TITLE
特性需求：股票一字涨停、跌停的，应该拒绝买单或卖单成交。

### ISSUE THREAD

**Issue by quant2008** [wondertrader/wondertrader#165]
股票一字涨停、跌停的，应该拒绝买单或卖单成交。期货也有此问题

**Comment by wondertrader** [comment]
dev分支已添加，但是方式略有不同，主要是根据K线的成交量来判断，如果K线成交量为0，就不触发撮合，这样通用性更强一些，详情可以看一下HisDataReplayer里面的实现

**Comment by quant2008** [comment]
不对吧，实盘中，一字涨停的k线会有成交的，但一般人买不到，所以处理成无法成交是合适的。
并不是无成交量。
