### ISSUE TITLE
HisDataReplayer的checkAllTicks 函数，有逻辑问题，它并不会check_all,只要它里面的第一个checkTicks 返回true， 后面的就不会调用

### ISSUE THREAD

**Issue by pdkuionline** [wondertrader/wondertrader#167]
我贴图片：
![FC3P R@IQ{EOC044%$KF~D6](https://user-images.githubusercontent.com/17922905/234791763-813f49b8-12cb-4876-9b2f-7b81cfc8a3f6.png)
下面是我的日志截图，也证实了这一情况:
![{YZJIZ}(O70ILLT J0~G UJ](https://user-images.githubusercontent.com/17922905/234791858-4a707ffa-a09d-4039-aa45-5491e58b9baa.png)

**Comment by wondertrader** [comment]
仔细看了一下这段代码，没有问题，这个就是自动检查并加载当日的tick数据。如果你的csv已经自动转成dsb，就不会再重新转换了，就没有日志输出。如果你怀疑这里有问题，可以在截图中的函数中去打一些日志看一下
![image](https://user-images.githubusercontent.com/62869597/236104599-96d7d0df-e38d-4031-bd9b-8a2362181e96.png)

**Comment by pdkuionline** [comment]
图中的日志已经证明了 这个函数的逻辑是有问题的。 其实是C++的基本功呀。  运算符 ||  ，  如果运算符左边 已经是true, 右边的表达式 根本不会去执行。

**Comment by wondertrader** [comment]
> 图中的日志已经证明了 这个函数的逻辑是有问题的。 其实是C++的基本功呀。 运算符 || ， 如果运算符左边 已经是true, 右边的表达式 根本不会去执行。

疏忽了，谢谢，已改
