### ISSUE TITLE
发现三个问题

### ISSUE THREAD

**Issue by sxen** [wondertrader/wondertrader#168]
一、INE与SHFE的分平今的期权未分，
二、CZCE的合约是月份是3位数，造成期权与期货分不清，造成转码出错，期货的转合约标准代码也是不正确的CZCE.AP.309 转出来的code还是309。
三、收盘后还有行情数据进来也会写入到历史行情里，拉起历史K线计算均价时，会出现多一条行情数据，行情波动大时就出现均线数值差距也很大。

**Comment by wondertrader** [comment]
我逐条回答：
1、可以解决，这个好弄
2、wt内部标准合约代码都是4位月份，底层会自动转换，郑商所的也使用4位月份
3、datakit有一个状态机，收盘后会在1分钟内接受新的行情，超出部分就不会再接收了。你的问题，我推测是你配置的收盘时间太长，导致状态机一直处于接收状态，你可以检查一下

**Comment by wondertrader** [comment]
问题一，dev已修复，正式版本请等0.9.8
