### ISSUE TITLE
HFT引擎中，缺少获取当前账户或策略所有持仓的接口

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#17]
HFT引擎中，缺少获取当前账户或策略所有持仓的接口

**Comment by wondertrader** [comment]
这个应该好了吧

**Comment by ZzzzHeJ** [comment]
ok，关闭吧


&nbsp;


胡尔杰

中国江苏省南京市

南京师范大学地理科学学院

地图学与地理信息系统专业

邮政编码：210000









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月4日(星期五) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wondertrader/wondertrader] HFT引擎中，缺少获取当前账户或策略所有持仓的接口 (Issue #17)





 
这个应该好了吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
