### ISSUE TITLE
一个组合多策略时，出现行情推送延时的情况

### ISSUE THREAD

**Issue by sxen** [wondertrader/wondertrader#172]
我的是HFT引擎一个组合绑定10个策略，运行一段时间后，会出现行情跟不上，会延时。而且运行时间越久，延时越久。不知道是不是我自己的问题。
datakit记录的tick是正常的。
当我只放一具策略时，策略接收的on_tick是正常没有延时的。只要同一组合绑定多了就会慢慢出现延时。

**Comment by wondertrader** [comment]
请检查两个地方：
1、是否为release环境，debug环境一定会慢
2、ontick响应的平均耗时是多少

**Comment by pdkuionline** [comment]
HFT 引擎是否会有多线程的问题？ 我看到 HFT策略里面，on_tick 和 on_order, 是没有经过同步的，并且，on_tick 运行在行情线程，on_order 运行在交易线程。

**Comment by wondertrader** [comment]
> 

肯定会出现的哦，线程间的互动还是要自己处理

**Comment by wondertrader** [comment]
> HFT 引擎是否会有多线程的问题？ 我看到 HFT策略里面，on_tick 和 on_order, 是没有经过同步的，并且，on_tick 运行在行情线程，on_order 运行在交易线程。

肯定会出现的哦，线程间数据同步还是要自己管理一下

**Comment by sxen** [comment]
查证是我策略订阅的合约多了，然后就会出现延时了，但去掉订阅，用windbg监控BUG，WtHftEngine::on_tick  这一行 uint32_t sid = it->first; 又报错了，或者是：WtHftEngine::on_tick 的

![image](https://github.com/wondertrader/wondertrader/assets/3351631/55dc6d71-8212-47ce-b439-76bb70d86c0e)
这个报错，

**Comment by sxen** [comment]
暂时我定位到的是stra_get_ticks出错，每次stra_get_ticks都会订阅一次，我在订阅时加多个判断，已订阅就不再订阅了，暂时就没再崩了，交易、获取tick，获取bar都可以正常。因为前面有时是好的，大部份是会崩溃闪退的。所以还要再挂着测试几天才行。

**Comment by sxen** [comment]
暂时定位到 stra_get_ticks 只要把stra_get_ticks里的订阅行情的代码注释掉就不会报错

**Comment by wondertrader** [comment]
这个问题，可能和我之前引用的一个hash容器有关，最新dev分支已经把hash容器升级了，你关注一下吧，对应的发布版本为0.9.8
