### ISSUE TITLE
在将csv转位dsb时volume仅支持整数

### ISSUE THREAD

**Issue by dogfood1** [wondertrader/wondertrader#173]
<img width="561" alt="image" src="https://github.com/wondertrader/wondertrader/assets/24435283/59174045-1846-40f0-8288-b082084bacf6">

在某些交易标的中可能存在volume为小数

请问是否可以直接把这里改为get_double 来解决这个问题

**Comment by wondertrader** [comment]
dev已改好，0.9.8会发布
