### ISSUE TITLE
生成解决方案时发生链接工具错误问题

### ISSUE THREAD

**Issue by VioletSakura777** [wondertrader/wondertrader#189]
生成解决方案的时候TraderMAOpt项目链接失败，无法解析外部符号。

**Comment by VioletSakura777** [comment]
![image](https://github.com/wondertrader/wondertrader/assets/53173560/21219419-0650-4e34-8fda-8e6ff78573c3)

**Comment by wondertrader** [comment]
这个是MAOpt接口不提供32位的库导致的，直接忽略该错误就可以了
