### ISSUE TITLE
[bug] WtUft TraderAdapter在品种数超过20个的情况下，运行出现coredump

### ISSUE THREAD

**Issue by wscjxky** [wondertrader/wondertrader#219]
# 问题描述
使用demo样例策略与配置运行
WtUft TraderAdapter在品种数超过20个的情况下，运行出现coredump
不超过的20个的情况下正常运行

# 临时解决
修改TraderAapter.h
1. 将wt_hashset改为fastest_hashset，或者改为std::unordered_set
3. 将wt_hashmap改为fastest_hashmap，或者改为std::unordered_map
问题解决

怀疑是ankerl hash在存储类指针的情况下实现有问题
# 问题代码
```
wt_hashmap<std::string, TraderAdapterPtr>
wt_hashset<ITrdNotifySink*>	_sinks;

```

![image](https://github.com/wondertrader/wondertrader/assets/21272297/c546e7cb-89e9-429f-bd60-b3e602600581)

**Comment by wondertrader** [comment]
超过20个品种，还是超过20个trader？

**Comment by wondertrader** [comment]
这个问题，我实盘下并没有重现，最多已经到30个合约对了

**Comment by wondertrader** [comment]
你可以试试看最新的0.9.9，我实盘下肯定没问题，实盘大概有接近30个策略，五六十个合约。issue我先关了，你如果能重现的话，再打开这个issue吧
