### ISSUE TITLE
回测模块中前后复权判断无法进入特定分支

### ISSUE THREAD

**Issue by brucehahah** [wondertrader/wondertrader#236]
![image](https://github.com/wondertrader/wondertrader/assets/146179203/2c022d1f-5d0b-487f-bfda-c7b78dfad1ca)
先对length做自减，会导致下一行判定语句永远为假，既flag不会等于1，建议将两个语句调换

**Comment by wondertrader** [comment]
已在dev中修复，正式版0.9.10发布
