### ISSUE TITLE
找不到libcurl-mdd.lib

### ISSUE THREAD

**Issue by anbull** [wondertrader/wondertrader#3]
#pragma comment(lib, "libcurl-mdd.lib")
libcurl.lib
libcurld.lib都好说，这libcurl-mdd.lib是curl的哪个版本的？

**Comment by wondertrader** [comment]
你好，标准依赖库已经放到这里了，因为比较大，所以没有放github。另外，你有什么问题也可以加QQ群直接问，谢谢关注
链接:https://pan.baidu.com/s/1Bdxh_PgjqHMzuGjl9ernhg 提取码:d6bh
