### ISSUE TITLE
游标问题

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#35]
以下部分应将判断改为大于，而不是大于等于
https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1617

https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1637

https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1657

https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1678

以下部分应该增加对游标的判断

https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1517

https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1544

https://github.com/wondertrader/wondertrader/blob/1b794d41da4dd7dc73f05f05b865f8f4b3bfa90a/src/WtBtCore/HisDataReplayer.cpp#L1571

**Comment by wondertrader** [comment]
已修复
