### ISSUE TITLE
WTSToolsLib编译出错

### ISSUE THREAD

**Issue by anbull** [wondertrader/wondertrader#4]
用最新的spdlog编译出错

WTSLogger.cpp 里面，
auto logger = std::make_shared<spdlog::logger>(catName, sinks);
sinks这个参数不能这么直接用？

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2664	“spdlog::logger::logger(spdlog::logger &&) noexcept”: 无法将参数 2 从“std::vector<spdlog::sink_ptr,std::allocator<_Ty>>”转换为“spdlog::sink_ptr”	WTSToolsLib	c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.16.27023\include\memory	1801

**Comment by wondertrader** [comment]
你好，标准依赖库已经放到这里了，因为比较大，所以没有放github。另外，你有什么问题也可以加QQ群直接问，谢谢关注
链接:https://pan.baidu.com/s/1Bdxh_PgjqHMzuGjl9ernhg 提取码:d6bh

**Comment by anbull** [comment]
> 你好，标准依赖库已经放到这里了，因为比较大，所以没有放github。另外，你有什么问题也可以加QQ群直接问，谢谢关注
> 链接:https://pan.baidu.com/s/1Bdxh_PgjqHMzuGjl9ernhg 提取码:d6bh

thanks a lot!

**Comment by wondertrader** [comment]
> > 你好，标准依赖库已经放到这里了，因为比较大，所以没有放github。另外，你有什么问题也可以加QQ群直接问，谢谢关注
> > 链接:https://pan.baidu.com/s/1Bdxh_PgjqHMzuGjl9ernhg 提取码:d6bh
> 
> thanks a lot!

不客气，如果没有问题，issue我先关了
