### ISSUE TITLE
多个执行器如何配置

### ISSUE THREAD

**Issue by Cheung0927** [wondertrader/wondertrader#46]
在查看官方和半官方的配置文件相关的教程时，和代码文件对比一看，发现有些差异，一时不知道怎么配置多个执行器好。请大佬帮忙解答，谢谢！！！

**Comment by wondertrader** [comment]
兄弟，这个提到讨论里的[QA](https://github.com/wondertrader/wondertrader/discussions/categories/q-a)吧
