### ISSUE TITLE
CentOS 编译项目报错

### ISSUE THREAD

**Issue by walter211** [wondertrader/wondertrader#6]
求助下各位C++大佬

编译一个项目的时候提示：
/lib/libboost_filesystem.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'

导致编译失败，找到一个类似的错误
https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring

说是因为用了不同版本的GCC编译导致C++11的ABI接口不兼容，有什么办法解决吗，尝试使用cmake的编译项-D_GLIBCXX_USE_CXX11_ABI 无效

版本信息:
centos 7.9
gcc 7.5
cmake 3.19
boost 1.72

**Comment by walter211** [comment]
尝试手动重新编译boost报同样错误

**Comment by wondertrader** [comment]
我研究一下

**Comment by wondertrader** [comment]
你好，CentOS7，默认安装gcc4.8，已经测试编译没有问题，只是需要重新编译boost才行，我会把centos7 + gcc4.8 + cmake3.19的依赖库放到网盘里，需要的话去群公告查一下网盘地址，下载一下就可以了
