### ISSUE TITLE
回测中，条件单跨日导致成交异常。

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#60]
在实盘中，每个交易开始于结束前，会对程序进行重启，会清空当前的条件单设置。
但是在回测中，可以在交易日的最后时刻设置条件单，并跨日。即便设置了tick撮合，在跨节假日时，由于前一天没有tick，撮合模式会自动转为模拟tick，当出现跳空时，条件单会成交在跳空间。从而导致绩效异常。
![@Y)FFVBS)$84I)XT0__739C](https://user-images.githubusercontent.com/41051523/163797308-fced6544-2923-45cc-8f7f-89b88551c7f5.png)
建议在回测中，每个交易日结束时，清空已有的条件单列表。

**Comment by wondertrader** [comment]
请用最新dev重新测试，应该已经解决
