### ISSUE TITLE
【HFT】在on_order或者on_trade中下单会触发指针悬空或边界溢出的问题

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#62]
# 问题描述

在HFT引擎的回测中，撮合是在on_tick下的procOrder函数中执行的。

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtBtCore/HftMocker.cpp#L633-L637

每次撮合时，会从_orders中获取对应的order对象，并触发on_order与on_order。如果此时在on_order与on_order的回调函数中，再次调用下单函数，会添加新的order对象到_orders中，添加的代码是异步执行的。

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtBtCore/HftMocker.cpp#L760-L763

在触发procOrder后，如果有成交，便会根据成交订单对应的localid，将订单从_orders中erase掉。

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtBtCore/HftMocker.cpp#L352-L356

上述过程有一定概率触发如下几个问题：

1. _orders中会存在本该被释放掉的localid键，而值则是一个空的order对象
2. 会在其他地方操作_orders时，触发越界错误

# 需要被修复的理由

尽管可以通过避免在on_order或者on_trade中下单来避开这个问题，但是在实际的策略设计中，可能会出现比较多需要在前一个订单成交后，立刻发出新订单的情况，如套利中的主被动腿订单。而且这个问题在实盘中实际是不会触发的，这是由于wt的撮合机制导致的。为了避免限制WT的下单限制，保证回测与实盘代码一致，因此需要修复该问题。

# 修复建议

采用一个额外的单独订单map来保存下单中创建的订单对象，并在每轮on_tick执行前，将该订单map合并到_orders中。

# 其他

触发错误的订单，总是在on_trade中交易的
![image](https://user-images.githubusercontent.com/41051523/165345579-b8867d97-d934-4680-9ae7-b6bd4b1cb084.png)

**Comment by wondertrader** [comment]
这个应该已经解决，orders改成了智能指针

**Comment by dongqiceo** [comment]
改成智能指针后不能解决这个问题

**Comment by dongqiceo** [comment]
![image](https://user-images.githubusercontent.com/12833625/203716427-ae210b5e-aa5b-4773-8274-2030873e863f.png)

**Comment by dongqiceo** [comment]
在ontick撮合时_orders循环里还是出现里野指针
