### ISSUE TITLE
[BUG] TWAP算法发现以下错误

### ISSUE THREAD

**Issue by ZzzzHeJ** [wondertrader/wondertrader#66]
# 在执行器中的TWAP执行单元下发现以下问题：

## 撤单日志缺少参数

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtExeFact/WtTWapExeUnit.cpp#L80-L85

第83行日志输出的format缺少一个参数

## 参数表述与实际存在差异

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtExeFact/WtTWapExeUnit.h#L100-L105

_total_secs和_tail_secs在备注中单位是秒，但在实际计算中，由于now的单位是毫秒，因此存在问题

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtExeFact/WtTWapExeUnit.cpp#L174-L177

## now时间不更新

https://github.com/wondertrader/wondertrader/blob/fd65a052d26be32882f89e8e9dfcd1d7b8736a3b/src/WtExeFact/WtTWapExeUnit.cpp#L159

now时间没有更新，始终指向当日的8:00

**Comment by wondertrader** [comment]
已经在dev修复了
