### ISSUE TITLE
XTP的三个问题

### ISSUE THREAD

**Issue by stonebj** [wondertrader/wondertrader#77]
1、XTP的cancel order返回非0值才代表正常，TraderXTP::orderAction里面写的是要求为0.
2、XTP有一个部分撤单的状态，需要映射到WT里面的完全撤单，否则WOS_PartTraded_NotQueuing这种状态无法触发on_order回调
3、XTP的lib没有自动重连，需要在OnDisconnect里面自己调用Login重新连接。
- ParserXTP里面，需要用DoLogin重新登录，以及行情也需要重新订阅（XTP QA）
- TraderXTP里面生成entrustid的逻辑，需要跟session_id解耦
> 10.问：api会自动重连么？
> 答：api不会自动帮用户重连。用户可以在收到断线通知OnDisconnect()后选择不销毁api，不登出，继续登录login()，此时交易服务器会在用户重新登录后，从断点消息处续传。注意：行情服务器在断线后不会重新推送行情，除非用户重新订阅。

> orderInsert函数里面，生成entrustid，用到了_sessionid
> 然后断线，重连，会受到断点续传的报单回调
> OnOrderEvent函数里面，根据order_info->order_client_id重新生成entrustid，这时候_sessionid变了，会导致entrustid不一致

**Comment by wondertrader** [comment]
dev已修复
